# Etapa de construcción
FROM node:18.16.0-slim AS builder

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar archivos de dependencias y prisma
COPY package*.json ./
COPY prisma ./prisma/

# Instalar dependencias necesarias para la construcción
RUN apt-get update && apt-get install -y \
    python3 \
    build-essential \
    && npm ci \
    && apt-get purge -y --auto-remove python3 build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copiar el resto de los archivos
COPY . .

# Ejecutar Prisma Generate y construir la aplicación
RUN npx prisma generate && npm run build

# Etapa final
FROM node:18.16.0-slim

# Instalar las dependencias necesarias para el desarrollo
RUN apt-get update && apt-get install -y --no-install-recommends libssl-dev && \
    rm -rf /var/lib/apt/lists/*

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar los archivos necesarios desde la etapa de construcción
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/prisma ./prisma
COPY --from=builder /usr/src/app/tsconfig.json ./

# Instalar dependencias de desarrollo
RUN npm install

# Exponer el puerto de la aplicación
EXPOSE 3000

# Comando para iniciar la aplicación en modo desarrollo
CMD ["npm", "run", "start:dev"]
