version: '3.8'

services:
  app:
    container_name: backend-unab
    image: backend-unab
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${{ secrets.DATABASE_URL }}
      - PORT=${{ secrets.PORT }}
    volumes:
      - .:/usr/src/app
    restart: always
