version: '3.8'

services:
  app:
    container_name: backend-unab
    image: backend-unab
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    restart: always
