version: '3.8'
services:
  app:
    container_name: backend-unab
    image: backend-unab
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        DATABASE_URL: ${DATABASE_URL}
        PORT: ${PORT}
    ports:
      - '${PORT}:${PORT}'
    restart: always
